# Generated by Django 2.0.7 on 2018-07-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baglam',
            name='fabl_id',
        ),
    ]
