# Generated by Django 2.0.7 on 2018-07-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0002_remove_baglam_fabl_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baglam',
            old_name='anantar',
            new_name='anahtar',
        ),
    ]
