# Generated by Django 2.0.7 on 2018-07-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0003_auto_20180729_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabl',
            name='tarih',
        ),
        migrations.RemoveField(
            model_name='fabl',
            name='yazar',
        ),
    ]
