# Generated by Django 2.0.7 on 2018-07-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0004_auto_20180730_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahne',
            name='anahtar',
            field=models.CharField(choices=[('Girizgah', 'Girizgah'), ('Serim', 'Serim'), ('Düğüm', 'Düğüm'), ('Çözüm', 'Çözüm'), ('Öğüt', 'Öğüt')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sahne',
            name='secenek',
            field=models.CharField(choices=[('İyi', 'İyi'), ('Kötü', 'Kötü')], max_length=1),
        ),
    ]
