# Generated by Django 2.0.7 on 2018-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0006_auto_20180730_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahne',
            name='anahtar',
            field=models.CharField(choices=[('G', 'Girizgah'), ('S', 'Serim'), ('D', 'Düğüm'), ('C', 'Çözüm'), ('O', 'Öğüt')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sahne',
            name='secenek',
            field=models.CharField(choices=[('I', 'İyi'), ('K', 'Kötü')], max_length=1),
        ),
    ]
