# Generated by Django 2.0.7 on 2018-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masal', '0007_auto_20180730_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahne',
            name='anahtar',
            field=models.CharField(choices=[('B', 'Başlık'), ('G', 'Girizgah'), ('S', 'Serim'), ('D', 'Düğüm'), ('C', 'Çözüm'), ('O', 'Öğüt')], max_length=1),
        ),
    ]
